Models/Absent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace school.Models
{
    public class Absent
    {
        public Absent()
        {
            DateAbsent = DateTime.Now;
        }

        [Key]
        public int Id { get; set; }
        [ForeignKey("StudentNavigation")]
        public int StudentId { get; set; }
        public DateTime DateAbsent { get; set; }
        [Display(Name = "الغيــاب")]

        public bool? AbsentCheck { get; set; }

        public virtual Student StudentNavigation { get; set; }
    }
}

Controllers/AbsentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using school.dtos;
using school.Models;

namespace school.Controllers
{
    public class AbsentController : Controller
    {
        private readonly SchoolContext context;
        public AbsentController(SchoolContext context)
        {
            this.context = context;
        }
        public async Task<IActionResult> Index() => View(await context.Absent.Select(a => a.DateAbsent.Month ).Distinct().ToListAsync());
        

        public async Task<IActionResult> Table(int month, int year)
        {
            
            int? cls = HttpContext.Session.GetInt32("Class");
            ViewData["Month"] = month;
            var students = await context.Student.Where(c => c.ClassFk == cls).ToListAsync();
            AbsentCelander absentCelander = new AbsentCelander()
            {
                month = month,
                year = year
            };

            absentCelander.SetNumOfDay();
            absentCelander.MatrixSet(students, context);
            return View(absentCelander);
        }

        public async Task<IActionResult> TimeAbsentTable(int? id)
        {
            var list = await context.Student.Where(s => s.ClassFk == id).ToListAsync();
            return View(list);
        }

    }
}

Views/Absent/Index.cshtml
@model IEnumerable<int>
@{
    ViewData["Title"] = "Index";
}

<nav class="navbar navbar-expand-sm navbar-dark justify-content-center">
    <ul class="navbar-nav">
        <li class="nav-item list-inline-item">
            <a class="nav-link" href="#">
                <div class="leftIcon">
                    <i class="fas fa-home" title="الصفحةُ الرئيسية"></i>
                </div>
            </a>
        </li>
        <li class="nav-item list-inline-item">
            <a class="nav-link" href="#">
                <div class="rightIcon">
                    <i class="fas fa-university" title="السنواتُ الدراسيّة"></i>
                </div>
            </a>
        </li>
    </ul>
</nav>


<div class="row2">
    @foreach (var month in Model)
    {

    <a asp-action="Table" asp-controller="Absent"
       asp-route-month="@month" asp-route-year="2020" title="الشهر @month">الشهر @month </a>
    }
</div>

<link rel="stylesheet" href="~/css/styleClasses.css" />
<script src="~/js/custom-classes.js"></script>

Views/Absent/Table.cshtml
@model school.dtos.AbsentCelander
@{
    ViewData["Title"] = "Table";
}

        <div id="cont">
            <div class="myH2">
                <div class="leftDiv">
                    <h2 class="left-1" id="stageTable"> : المرحلةُ الدراسيّة</h2>
                    <h2 class="left-2" id="classTable"> : الفصلُ الدراسيّ</h2>
                </div>
                <div class="rightDiv">
                    <h2 class="right-h2" id="schoolTable"> : اسمُ المدرسة</h2>
                    <h2 class="right-h2"> @Model.month : سردٌ لغياب شهر</h2>
                </div>
                <div class="clear"></div>
                <hr>
                <h2 class="centerized"> : كشفُ أسماء لغياب طُلاب فصل</h2>
            </div>

            <table style="width: 100%; margin-left:auto; margin-right:auto;" border="1" >

                <thead style="background-color: #dfe4ea;" >
                    <tr>


                        @for (int i = 1; i <= Model.NumOfDay; i++)
                        {
                            if (Model.endDate.DayOfWeek == DayOfWeek.Saturday)
                            {
                                <th scope="col" class="th-edit">س</th>
                            }
                            if (Model.endDate.DayOfWeek == DayOfWeek.Sunday)
                            {
                                <th scope="col" class="th-edit">ح</th>
                            }
                            if (Model.endDate.DayOfWeek == DayOfWeek.Monday)
                            {
                                <th scope="col" class="th-edit">ن</th>
                            }
                            if (Model.endDate.DayOfWeek == DayOfWeek.Tuesday)
                            {
                                <th scope="col" class="th-edit">ث</th>
                            }
                            if (Model.endDate.DayOfWeek == DayOfWeek.Wednesday)
                            {
                                <th scope="col" class="th-edit">ع</th>
                            }
                            if (Model.endDate.DayOfWeek == DayOfWeek.Thursday)
                            {
                                <th scope="col" class="th-edit">خ</th>
                            }
                            if (Model.endDate.DayOfWeek == DayOfWeek.Friday)
                            {
                                <th scope="col" class="th-edit">ج</th>

                            }

                            Model.endDate = Model.endDate.AddDays(-1);

                        }
                        <th scope="col" class="th-edit" style="font-size: 12px; width: 7.8%;">اسم الطالب</th>
                    </tr>

                </thead>
                <tbody style="text-align: center;">
                    @for (int i = 0; i < Model.Students.Length; i++)
                    {
                    <tr>

                        @for (int j = Model.NumOfDay - 1; j >= 0; j--)
                        {
                            if (Model.absentMat[i, j] != null)
                            {
                                if (Model.absentMat[i, j].Value)
                                {
                                    <td scope="col"><i class="fa fa-times"></i></td>

                                }
                                if (!Model.absentMat[i, j].Value)
                                {
                                    <td scope="col"><i class="fas fa-check"></i></td>

                                }
                            }
                            else
                            {
                                <td scope="col">_</td>
                            }
                        }
                        <td scope="col" style="font-size: 12px; width: 7.8%;">@Model.Students[i]</td>
                    </tr>
                    }
                </tbody>
            </table>
            <br>
            <br />
        </div>
        <div class="form-control">
            <input value="اطبع" class="btn btn-danger" onclick="return print('absentPaper')" type="button" tabindex="1"
                   style="margin-left:1%; width:140px; background-color:#0984e3; color:#FFFFFF; cursor:pointer;
            font-size:16px; border: solid 2px #0984e3; border-radius:10px;" />
        </div>  
<link href="~/css/showAbsentsThePage.css" rel="stylesheet" />

Views/Absent/TimeAbsentTable.cshtml
@model IEnumerable<Student>
@{
    ViewData["Title"] = "حصيلت الغياب";
}
<div id="newDiv">
    <nav class="newNavBarForSmall">
        <input type="checkbox" id="checkMyBar">
        <label for="checkMyBar" class="checkBTN" id="checkBTN">
            <i class="fas fa-bars"></i>
        </label>
        <ul>
            <li>
                <a class="active" id="anchorItem" href="#"><i class="fas fa-home" title="الصفحةُ الرئيسية"></i></a>
            </li>
            <li>
                <a class="active" href="#"><i class="fas fa-university" title="السنواتُ الدراسيّة"></i></a>
            </li>
            <li>
                <a class="active" href="#"><i class="fas fa-chalkboard-teacher" title="الفُصول الدراسيّة"></i></a>
            </li>
            <li>
                <a class="active" href="#"><i class="fas fa-book-reader" title="الذهابُ إلى بيانات الفصل الحالي للتعديل"></i></a>
            </li>
            <li>
                <a class="nav-link" href="#" onclick="printThePageNow()"><i class="fas fa-print" title="طباعة الآن"></i></a>
            </li>
        </ul>
    </nav>
</div>

<div class="row">
    <div class="container" style="margin-top: 120px;">
        <div class="table-responsive table-striped">
            <table class="table table-striped m-0" id="myTable">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">لم يحضر رغم الانذار</th>
                        <th scope="col">عدد الاناذير</th>
                        <th scope="col">غياب منقطع</th>
                        <th scope="col">غياب متصل</th>
                        <th scope="col">اسمُ الطالب</th>
                        <th scope="col">#</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var student in Model)
                    {
                        <tr>
                            <td>
                                @if (student.IsReject)
                                {
                                    <span class="numberOfAbsentOfStudent" tabindex="5">نعم</span>
                                }
                                else
                                {
                                    <span class="numberOfAbsentOfStudent" tabindex="5">لا</span>

                                }
                            </td>
                            <td>
                                <span class="numberOfAbsentOfStudent" tabindex="4">@student.NumOfReject</span>

                            </td>
                            <td>
                                <span class="numberOfAbsentOfStudent" tabindex="3">@student.TimeAbsent</span>
                            </td>
                            <td>
                                <span class="numberOfAbsentOfStudent" tabindex="2">@student.TimeAbsentDaily</span>
                            </td>
                            <td tabindex="1">@student.StudentName</td>
                            <th scope="row" hidden>@student.StudentId</th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!--=================================================================================================================================-->
        <!--This is for adding the student for the another class-->

        <div class="modal fade" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">نقلُ الطالب</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal fade" id="exampleModalForSetting" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalLabelOfNewPassword">تعديلُ كلمة المُرور</h5>
                                </div>
                                <div class="modal-body">
                                    <form>
                                        <div class="form-group">
                                            <input type="password" class="form-control" id="oldPassword" placeholder="كلمةُ المُرور القديمة"><br><br>
                                            <input type="password" class="form-control" id="newPassword" placeholder="كلمةُ المُرور الجديدة">
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">غلقُ الأيقونة</button>
                                    <button type="button" class="btn btn-primary">تعديلُ الآن</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="search" id="searchInput">
                        <form class="search-form">
                            <input type="text" id="myInputForSearching" onkeyup="functionForSearchingInTable()" placeholder=" .... ابحَثْ عن طالبٍ في الفصلِ الحالي" tabindex="1">
                            <input type="submit" value="بحث">
                        </form>
                    </div>
                    <!-- Modal body -->
                    <div class="modal-body bodyOfTheEditingModal">
                        <form class="form-inline">

                            <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                                <option selected>الفصلُ المُراد نقل الطالب له...</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>

                            <button type="submit" class="btn btn-primary my-1">حفظُ التغييرات</button>
                        </form>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger closeTheEditingModal" data-dismiss="modal">غلقُ التعديلات</button>
                    </div>

                </div>
            </div>
        </div>
        <!--=================================================================================================================================-->
        <!--This is for the checking the editing operation-->
        <!-- Button trigger modal -->
        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">تعديلُ الاسم الخاص بالطالب</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="اسمُ الطالب بعد التعديل" aria-describedby="basic-addon2" disabled>
                        </div>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="اسمُ الطالب بعد التعديل" aria-describedby="basic-addon2">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">إلغاء</button>
                        <button type="button" class="btn btn-primary">حِفظُ التعديل الآن</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="js/timeOfAbsents.js "></script>
<link rel="stylesheet" href="~/css/timeOfAbsents.css" />